import { Heart, Plus, Star } from "lucide-react";
import { Link } from "@tanstack/react-router";
import type { Product } from "@/lib/catalog";
import { formatPrice } from "@/lib/catalog";
import { useStore } from "./store-context";
import { Button } from "@/components/ui/button";
export function ProductCard({product}:{product:Product}){const {add,toggleWish,wishlist}=useStore();const wished=wishlist.includes(product.id);return <article className="group flex min-w-0 flex-col overflow-hidden rounded-lg border border-border bg-card transition hover:-translate-y-0.5 hover:shadow-lg">
 <div className="relative overflow-hidden bg-muted"><Link to="/product/$id" params={{id:product.id}}><img src={product.image} alt={product.name} loading="lazy" width={1008} height={1008} className="aspect-square w-full object-cover transition duration-300 group-hover:scale-[1.03]"/></Link>{product.badge&&<span className="absolute left-2 top-2 rounded-sm bg-deal px-2 py-1 text-[11px] font-bold text-deal-foreground">{product.badge}</span>}<Button variant="secondary" size="icon" aria-label={wished?"Remove from wishlist":"Add to wishlist"} onClick={()=>toggleWish(product.id)} className="absolute right-2 top-2 rounded-full shadow-sm"><Heart className={wished?"fill-primary text-primary":""}/></Button></div>
 <div className="flex flex-1 flex-col p-3 sm:p-4"><p className="text-xs font-medium text-muted-foreground">{product.pack}</p><Link to="/product/$id" params={{id:product.id}} className="mt-1 line-clamp-2 min-h-10 text-sm font-bold leading-5 text-foreground hover:text-primary">{product.name}</Link><div className="mt-2 flex items-center gap-1 text-xs"><Star className="size-3.5 fill-rating text-rating"/><b>{product.rating}</b><span className="text-muted-foreground">({product.reviews})</span></div><div className="mt-auto flex items-end justify-between gap-2 pt-3"><div><span className="text-lg font-extrabold">{formatPrice(product.price)}</span>{product.mrp && <span className="ml-1 text-xs text-muted-foreground line-through">{formatPrice(product.mrp)}</span>}</div><Button size="sm" onClick={()=>add(product.id)} aria-label={`Add ${product.name} to cart`}><Plus/> <span className="hidden sm:inline">Add</span></Button></div></div>
 </article>}
